### ISSUE TITLE
2.0.0 Heimdall [V2 Beta] +2 configs

### ISSUE THREAD

**Issue by panfr0st** [panfr0st/heimdall#7]
![image](https://user-images.githubusercontent.com/82876098/115995409-c9d3c880-a626-11eb-803f-663ea7d8a780.png)
**New menu**
**Better functions**
**Beta**

![image](https://user-images.githubusercontent.com/82876098/115995432-e5d76a00-a626-11eb-912f-8913276537e6.png)
![image](https://user-images.githubusercontent.com/82876098/115995443-f12a9580-a626-11eb-9a80-dc833eedf362.png)
![image](https://user-images.githubusercontent.com/82876098/115995453-fdaeee00-a626-11eb-96e9-01610e9cd27f.png)

In addition, customer role received a two CFG's configured with Heimdall v2 already.

**Comment by Mooni10** [comment]
hello when i use your java script my game go like this.
![image](https://user-images.githubusercontent.com/83175621/115999287-1b5a6400-a5e3-11eb-9af3-5f835fd199e3.png)

**Comment by dzkr5** [comment]
> hello when i use your java script my game go like this.
> ![image](https://user-images.githubusercontent.com/83175621/115999287-1b5a6400-a5e3-11eb-9af3-5f835fd199e3.png)

I think its cfg issue restart game (I had the same thing and when I restarted it was all right)

**Comment by panfr0st** [comment]
Fixed at https://github.com/panfr0st/heimdall/issues/8

Thanks for report.
